#!/usr/bin/env bash
#
# Create worktrees for a feature branch across multiple sub-repos.
#
# Usage:
#   ./worktree-create.sh <branch> [repo1 repo2 ...]
#
# If no repos are specified, creates worktrees for ALL standard (non-worktree)
# repos in workspace.conf. Creates the branch in each repo if it doesn't exist.
#
# Worktree directories are named: <repo>--<sanitized-branch>
# Entries are appended to workspace.conf and .gitignore automatically.
# Run ./bootstrap.sh after to wire up .claude/ symlinks.

set -euo pipefail
cd "$(dirname "$0")"

if [ ! -f workspace.conf ]; then
  echo "Missing workspace.conf" >&2
  exit 1
fi

if [ $# -lt 1 ]; then
  echo "Usage: $0 <branch> [repo1 repo2 ...]" >&2
  echo "" >&2
  echo "Examples:" >&2
  echo "  $0 feature/auth              # all repos" >&2
  echo "  $0 feature/auth web-app api  # specific repos" >&2
  exit 1
fi

# shellcheck source=/dev/null
source workspace.conf

BRANCH="$1"
shift
SELECTED_REPOS=("$@")

sanitize_branch() {
  echo "$1" | sed 's/[^a-zA-Z0-9._-]/-/g'
}

SAFE_BRANCH=$(sanitize_branch "$BRANCH")

# Collect standard (non-worktree) repo names
get_standard_repos() {
  local repos=()
  for entry in "${REPOS[@]}"; do
    IFS='|' read -r name url_or_ref _ <<< "$entry"
    if [[ "$url_or_ref" != worktree:* ]]; then
      repos+=("$name")
    fi
  done
  echo "${repos[@]}"
}

if [ ${#SELECTED_REPOS[@]} -eq 0 ]; then
  read -ra SELECTED_REPOS <<< "$(get_standard_repos)"
fi

# Validate that selected repos exist in workspace.conf as standard clones
for repo in "${SELECTED_REPOS[@]}"; do
  found=false
  for entry in "${REPOS[@]}"; do
    IFS='|' read -r name url_or_ref _ <<< "$entry"
    if [ "$name" = "$repo" ] && [[ "$url_or_ref" != worktree:* ]]; then
      found=true
      break
    fi
  done
  if [ "$found" = false ]; then
    echo "Error: '$repo' is not a standard repo in workspace.conf" >&2
    exit 1
  fi
done

CREATED=()

for repo in "${SELECTED_REPOS[@]}"; do
  wt_name="${repo}--${SAFE_BRANCH}"

  # Skip if worktree already exists
  if [ -d "$wt_name" ] || [ -f "$wt_name/.git" ]; then
    echo "Skipping $wt_name (already exists)"
    continue
  fi

  if [ ! -d "$repo/.git" ]; then
    echo "Error: source repo '$repo' not cloned. Run ./bootstrap.sh first." >&2
    exit 1
  fi

  echo "Creating worktree: $wt_name (branch: $BRANCH) from $repo..."

  # Fetch latest to ensure we have remote branch if it exists
  git -C "$repo" fetch --quiet 2>/dev/null || true

  # Create branch from remote if it exists there, otherwise from HEAD
  if ! git -C "$repo" rev-parse --verify "$BRANCH" >/dev/null 2>&1; then
    if git -C "$repo" rev-parse --verify "origin/$BRANCH" >/dev/null 2>&1; then
      git -C "$repo" branch "$BRANCH" "origin/$BRANCH"
    else
      git -C "$repo" branch "$BRANCH"
    fi
  fi

  git -C "$repo" worktree add "../$wt_name" "$BRANCH"
  CREATED+=("$wt_name")
done

if [ ${#CREATED[@]} -eq 0 ]; then
  echo "No new worktrees created."
  exit 0
fi

# Append worktree entries to workspace.conf
for repo in "${SELECTED_REPOS[@]}"; do
  wt_name="${repo}--${SAFE_BRANCH}"
  entry="  \"${wt_name}|worktree:${repo}|${BRANCH}\""

  # Only append if not already in workspace.conf
  if ! grep -qF "$wt_name|worktree:" workspace.conf; then
    # Insert before the closing paren of REPOS=(...)
    sed -i '' "/^)/i\\
${entry}" workspace.conf
  fi
done

# Append worktree dirs to .gitignore
for wt_name in "${CREATED[@]}"; do
  if ! grep -qxF "${wt_name}/" .gitignore 2>/dev/null; then
    # Insert after the sub-repos block (first blank line after repo dirs)
    sed -i '' "/^# Generated by bootstrap.sh/i\\
${wt_name}/" .gitignore
  fi
done

echo ""
echo "Created ${#CREATED[@]} worktree(s) for branch '$BRANCH':"
for wt_name in "${CREATED[@]}"; do
  echo "  $wt_name/"
done
echo ""
echo "Run ./bootstrap.sh to wire up .claude/ symlinks."
